doctrine_migrations:
  migrations_paths:
    'BitBag\OpenMarketplace\Migrations': '%kernel.project_dir%/src/Migrations'
  em: default
  storage:
    table_storage:
      table_name: 'doctrine_migration_versions'
      version_column_name: 'version'
      version_column_length: 192
      executed_at_column_name: 'executed_at'
  organize_migrations: false
  all_or_nothing: false
  check_database_platform: true
  enable_profiler: false
