imports:
    - { resource: "state_machine/**/*.yml" }
    - { resource: 'resources/*.yml' }
    - { resource: 'services.xml' }
    - { resource: 'grids.yml' }
    - { resource: 'email/*.yml'}
    - { resource: "ui.yml"}
    - { resource: "fixtures.yml"}
